/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventure;

import java.io.IOException;

import adventure.days.day_7.DaySevenSolution;
import adventure.days.day_8.DayEightSolution;


public class App {
  

    public static void main(String[] args) throws IOException 
    {

        System.out.println(DayEightSolution.partOneSolution());
        // System.out.println(DaySevenSolution.partTwoSolution());

    }
}
