/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventure;

import java.io.IOException;

import adventure.days.DayBase;
import adventure.days.day_1.DayOneSolution;
import lombok.SneakyThrows;


public class App {


    @SneakyThrows
    public static void main(String[] args) throws IOException
    {

        DayBase day = new DayOneSolution();
//        System.out.println(day.SolutionPartOne());
        System.out.println(day.SolutionPartTwo());

    }
}
